spring.application.name=api-mongodb


spring.mongodb.uri=mongodb+srv://boeingped:pedro@cluster0.y4jajgo.mongodb.net/escola_ti?appName=Cluster0

server.port=${PORT:8080}

# Configuração de Upload de Arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB